# Generated by Django 5.2.4 on 2025-07-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgs',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
